---
# run roles based on certain params
skip_prereqs: false
force_minishift_install: false
setup_minishift: true
start_minishift: true
force_repo_clone: true
setup_jenkins: true
setup_fedmsg: true
setup_containers: true

# default location for minishift
minishift_dest_dir: "{{ ansible_env.HOME }}/minishift"

# default minishift profile name
profile: minishift

# disk and memory size
disk_size: 40gb
memory: 6400mb

# base device size
# for rootfs in pods
basedevice_size: 20G

# minishift iso location
minishift_iso: http://artifacts.ci.centos.org/fedora-atomic/minishift/iso/minishift.iso

# repo to clone
pipeline_repo: https://github.com/CentOS-PaaS-SIG/ci-pipeline

# repo directory
pipeline_dir: "{{ ansible_env.HOME }}/minishift/ci-pipeline"

# repo refspec
pipeline_refspec: '+refs/pull/*:refs/heads/*'

# repo branch or sha
pipeline_branch: 'master'

# cluster username
username: developer

# cluster password
password: developer

# cluster admin username
admin_username: system

# cluster admin password
admin_password: admin

# project for openshift
project: continuous-infra

# Jenkins infra buildconfig templates:
jenkins_bc_templates:
  - jenkins/jenkins-persistent
  - jenkins/jenkins-continuous-infra-slave

# Pipeline container buildconfig templates:
pipeline_bc_templates:
  - rpmbuild/rpmbuild
  - rsync/rsync
  - ostree_compose/ostree_compose
  - ostree-image-compose/ostree-image-compose
  - ostree-boot-image/ostree-boot-image
  - singlehost-test/singlehost-test
  - linchpin_libvirt/linchpin_libvirt

# fedmsg relay buildconfig templates:
fedmsg_bc_templates:
  - fedmsg-relay/fedmsg-relay

# modify tags on images
modify_tags: true

# tag to use
tag: stable

# modify security context contraints (SCC) to run privileged containers
modify_scc: true

# enable the sample pipeline
# Note: This will eventually moved to an example project repo)
enable_sample_pipeline: true

# These are parameters that are passed to setup the containers for the pipeline
PARAMS:
  - key: REPO_URL
    val: https://github.com/arilivigni/ci-pipeline
  - key: REPO_REF
    val: master
  - key: ENABLE_VM
    val: false
  - key: VM_IMG_URL
    val: http://artifacts.ci.centos.org/artifacts/fedora-atomic/f26/images/latest-atomic.qcow2
